### ISSUE TITLE
At install process it hang and freeze after Test Docker

### ISSUE THREAD

**Issue by elohffa** [bmcgonag/subspace_install_script#1]
********    Test Docker With Hello World    ********

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

**Comment by bmcgonag** [comment]
I've not been able to get subspace to work for quite some time now, even installing it manually, so I created a project of my own for the same purpose at https://github.com/bmcgonag/Vector

I'll remove the docker test, and you're welcome to try again.
